# Generated by Django 5.1.1 on 2024-09-11 07:05

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('BOLETO', 'Boleto'), ('TRANSFERENCIA_BANCARIA', 'Transferência bancária')], max_length=100, verbose_name='Tipo de pagamento')),
                ('validity', models.DateField(default=django.utils.timezone.now, verbose_name='Validade')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de inicio')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de fim')),
                ('adjustments', models.FloatField(default=0, verbose_name='Ajustes previstos')),
                ('is_active', models.BooleanField(default=False, verbose_name='contrato encerrado')),
                ('devolution_reason', models.CharField(max_length=100, verbose_name='Motivo da devolução')),
                ('compliant', models.BooleanField(default=False, verbose_name='adimplente')),
                ('defaulter', models.BooleanField(default=False, verbose_name='inadimplente')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('APARTAMENTO', 'Apartamento'), ('CASA', 'Casa'), ('COMERCIAL', 'Comercial')], max_length=100, verbose_name='Tipo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('address', models.CharField(max_length=150, verbose_name='Endereço')),
                ('room_number', models.IntegerField(default=1, verbose_name='Numero de quartos')),
                ('parking_space', models.IntegerField(default=1, verbose_name='Vagas de estacionamento')),
                ('rental_value', models.FloatField(default=0, verbose_name='Valor de aluguel')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('rented', models.BooleanField(default=False, verbose_name='Alugado')),
                ('maintenance', models.BooleanField(default=False, verbose_name='Em manutenção')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('telephone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('is_owner', models.BooleanField(default=False, verbose_name='é proprietario?')),
                ('is_tenant', models.BooleanField(default=False, verbose_name='é inquilino?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Gestor')),
                ('is_operator', models.BooleanField(default=False, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_payed', models.FloatField(default=0, verbose_name='Valor pago')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data do pagamento')),
                ('contratc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.contratcs', verbose_name='tipo de pagamento')),
            ],
        ),
        migrations.AddField(
            model_name='contratcs',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.property', verbose_name='Imovel'),
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.contratcs', verbose_name='Contrato')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.property', verbose_name='Imovel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users', verbose_name='inquilino')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users', verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.payments', verbose_name='pagamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users', verbose_name='proprietario')),
            ],
        ),
        migrations.AddField(
            model_name='contratcs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users', verbose_name='Usuario'),
        ),
    ]
