# Generated by Django 5.1.1 on 2024-09-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_users_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratcs',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(choices=[('BOLETO', 'Boleto'), ('TRANSFERENCIA_BANCARIA', 'Transferência bancária')], default='BOLETO', max_length=100, verbose_name='Tipo de pagamento'),
        ),
    ]
