# Generated by Django 5.1.1 on 2024-09-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_contratcs_payment_type_payments_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='available',
            new_name='avaliable',
        ),
    ]
