# Generated by Django 5.1.1 on 2024-09-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_property_rental_value_contratcs_rental_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contratcs',
            new_name='Contracts',
        ),
    ]
