# Generated by Django 5.1.1 on 2024-09-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_contratcs_contracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='validity',
            field=models.CharField(max_length=100, verbose_name='vigencia do contrato'),
        ),
    ]
