# Generated by Django 5.1.1 on 2024-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_contracts_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='adjustments',
            field=models.FloatField(default=0, null=True, verbose_name='reajustes previstos'),
        ),
    ]
