# Generated by Django 5.1.1 on 2024-09-20 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_contracts_adjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Pagamento efetuado?'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users', verbose_name='inquilino'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='contratc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.contracts', verbose_name='tipo de contrato'),
        ),
    ]
