# Generated by Django 5.1.1 on 2024-09-20 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_payments_payed_alter_contracts_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='contratc',
        ),
        migrations.AddField(
            model_name='payments',
            name='contract',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='api.contracts', verbose_name='contrato'),
        ),
    ]
