# Generated by Django 5.1.1 on 2024-09-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_payments_contratc_payments_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='rental_value',
        ),
        migrations.AddField(
            model_name='property',
            name='rental_value',
            field=models.FloatField(default=0, verbose_name='Valor de aluguel'),
        ),
    ]
