# Generated by Django 5.1.1 on 2024-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_contracts_rental_value_property_rental_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='rental_value',
            field=models.FloatField(default=0, verbose_name='Valor de aluguel'),
        ),
    ]
