# Generated by Django 5.1.1 on 2024-09-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_contracts_rental_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracts',
            old_name='user',
            new_name='tenant',
        ),
    ]
