# Generated by Django 5.1.1 on 2024-09-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_contracts_taxa_imobiliaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasse',
            name='imobiliaria_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='repasse',
            name='proprietario_value',
            field=models.FloatField(default=0),
        ),
    ]
