# Generated by Django 5.1.1 on 2024-09-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_user_property_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='owner',
            new_name='user',
        ),
    ]
